#!/usr/bin/env bash

# Define a state file
STATE_FILE="/tmp/hypr_fullscreen_state"

# Read the current state or default to 'off'
if [[ -f "$STATE_FILE" ]]; then
    STATE=$(cat "$STATE_FILE")
else
    STATE="off"
fi

# Toggle the state and execute the corresponding script
if [[ "$STATE" == "on" ]]; then
    # Switch to "off" state and run the 'window' script
    echo "off" > "$STATE_FILE"
hyprctl keyword general:gaps_in 5
hyprctl keyword general:gaps_out 10
hyprctl keyword general:border_size 2

pkill -SIGUSR1 waybar

    ~/.local/bin/window
else
    # Switch to "on" state and run the 'fullscreen' script
    echo "on" > "$STATE_FILE"
hyprctl keyword general:gaps_in 0
hyprctl keyword general:gaps_out 0
hyprctl keyword general:border_size 0

pkill -SIGUSR1 waybar

fi
